version: '3.9'

services:
  backend:
    build: backend
    ports:
      - "8080:8080"
    networks:
      - jwt-network
    depends_on:
      - jwt

  frontend:
    build: Frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

  jwt:
    image: mysql
    restart: always
    networks:
      - jwt-network
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3310:3306'
    expose:
      - '3310'
    volumes:
      - jwt:/var/lib/mysql

networks:
  jwt-network:
volumes:
  jwt: